### PR TITLE
Add new github action workflows

### PR DESCRIPTION
**Pull request by adam-cattermole**
Our CI/CD has stopped working as travis is now paid for. GitHub actions has been around for a while and seems appropriate to move to instead - quickly knocked up some test workflows to see if we can get it back up and running.

### CODE REVIEW

**Comment by adam-cattermole** [comment]
This now builds and tests on various cabal versions (8.6, 8.8, 8.10, 9.0), as well as using the stack.

I could not build the examples using the Makefiles with Cabal exec and v2-* cabal install, and so the examples are built only using stack.

It appears this works fine, but one of the tests is failing:

```
* Tests:     77
* Passed:    76
* Pending:   0
* Failures:  1
* Errors:    0
* Timed out: 0
* Filtered:  0

* Failures:
  * Striot.Jackson:outputRate_filter (src/Striot/Jackson.hs:377)
  
  * expected: 1.0
  * but got:  2.5
```

Once this is merged I'll check if the deploy workflow is working as intended.

**Comment by jmtd** [comment]
Thanks for this!

**Comment by jmtd** [comment]
I think the current versions of Debian (and probably Ubuntu) ship librdkafka now. Do we still need to use the external repo?

**Comment by adam-cattermole** [comment]
That's a good question - I know Ubuntu has had it for a while but last I checked it was quite an old version (0.7 or something) missing some performance enhancements.

**Comment by adam-cattermole** [comment]
Just quickly changed the workflow to use librdkafka from the Ubuntu repository

**Pull request merged**
