### PR TITLE
Changes to use aeson for serialisation

### PR DESCRIPTION
**Pull request by adam-cattermole**
As noted in issue #15, I have found that the serialisation to and from `String`s using `show` and `read` is currently a major overhead of the pipeline. This change uses the [aeson](https://hackage.haskell.org/package/aeson) JSON encoding library instead, where we are able to improve throughput from < 5,000 mps to ~22,000 mps.

### CODE REVIEW

**Comment by adam-cattermole** [comment]
After further testing with this library I have discovered an issue - whilst we are able to achieve much higher throughputs, there is also the introduction of a space leak. I'm unsure whether this is present in the current master version of the pipeline (and only coming to light at higher message rates), but I can not seem to find a way to eliminate it. For reference on my test platform at ~22,000 mps, within 30 seconds the sink has accumulated over 1GB of memory, and does not release it even if the connection is closed.

I would refrain from merging this for the time being and I will search for the root of the issue or an alternative solution.

**Comment by adam-cattermole** [comment]
I did change the testing methodology a little also, so not _all_ of the speedup can be attributed to the [aeson](https://hackage.haskell.org/package/aeson) package, but there is considerable documentation on the slow nature of `String`.

I'm going to try the [binary](https://hackage.haskell.org/package/binary) package next for comparison.

**Comment by adam-cattermole** [comment]
Now that I have sufficiently tested the changes in this PR, and also determined that the space leak is not related to these changes, I am happy for this to be merged, assuming you have not found any issues @jmtd.

**Comment by jmtd** [comment]
Hi @adam-cattermole , after a long delay (Holiday for a week, work stuff backed up etc.) I'm looking at this properly today. It's looking good! I'm learning a lot as I go (first experience of AESON, and Generic types).

**Pull request merged**
