### PR TITLE
Modify Nodes / Taxi reducing laziness

### PR DESCRIPTION
**Pull request by adam-cattermole**
I have taken some time to re-implement Nodes.hs in terms of Conduit. I think that this makes more sense than trying to manage the Socket connections ourselves. This also reduces the amount of laziness introduced during the input / output from Sockets.

We now do the following:

- Handle upstream connections through `processSocketC`. This spawns a new thread in `acceptConnectionsC`, deserialising and writing Events to a **bounded** channel, strictly one event at a time. `processSocketC` returns a lazy list of `IO` reads to this channel
- The `nodeX` function applies the stream operator to the lazy `IO` list the same as before
- `sendStreamC` has been introduced to write to the downstream, yielding the lazy list to conduit to process Events one by one - serialising and sending to the next node

There are some additional functions to handle some complications. The standard `recv` function internally reads 4096 bytes at a time from the socket. This required providing an `Event` termination character for any `Event` larger than this. I have currently set this to the NULL character (`\NUL` or `\0`) but I am open to suggestions on an alternative. I am using [attoparsec](http://hackage.haskell.org/package/attoparsec-0.12.1.0) to search for this character within incoming  `ByteString`s to re-build our `Event`s.

The bounded queue is a temporary fix for the issue with Taxi - I have set it as `chanSize = 10`, but realistically this value should be application dependant, so a better solution might be to create some kind of `StriotConfig` record that we can pass in with parameters.

Finally, I have added strictness annotations to the fields in the Taxi records in an attempt to reduce the number of suspensions built up by the large numbers of references between the fields.

### CODE REVIEW

**Comment by adam-cattermole** [comment]
One thing I forgot to mention - the `PortNumber` is now an `Int` again, and so I have updated `CompileIoT` to reflect this change.

**Comment by jmtd** [comment]
Sorry @adam-cattermole I haven't got around to reviewing this properly yet; I will try to do so this week.

**Comment by adam-cattermole** [comment]
Don't worry about this PR for now. I have found that some of the networking changes here haemorrhage performance drastically - I am working on a solution and will submit a new pull request with the Taxi specific changes for the time being.

**Comment by jmtd** [comment]
Hi @adam-cattermole: OK, thanks. Coincidentally I started to look at it last night, but only briefly. I did not attempt performance measurements. Looking just at the diffs, it seemed very clean, very good. I always enjoy reviewing your work. Let me know when you have something you'd like me to look over, even if it's not ready for merge.

**Comment by adam-cattermole** [comment]
Thanks @jmtd, I'll make sure to get some more of the work I'm doing available through PR's here!

**Pull request closed without merging**
